BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Categories" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"description"	TEXT,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Tags" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Users" (
	"id"	INTEGER,
	"userName"	VARCHAR(255),
	"password"	VARCHAR(255),
	"email"	VARCHAR(255),
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Works" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"description"	TEXT,
	"price"	FLOAT,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"CategoryId"	INTEGER,
	FOREIGN KEY("CategoryId") REFERENCES "Categories"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "WorkTag" (
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"TagId"	INTEGER NOT NULL,
	"WorkId"	INTEGER NOT NULL,
	FOREIGN KEY("TagId") REFERENCES "Tags"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("WorkId") REFERENCES "Works"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("TagId","WorkId")
);
CREATE TABLE IF NOT EXISTS "SequelizeMeta" (
	"name"	VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("name")
);
CREATE TABLE IF NOT EXISTS "WorkAssets" (
	"id"	INTEGER,
	"caption"	TEXT,
	"type"	VARCHAR(255),
	"reference"	VARCHAR(255),
	"order"	INTEGER,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"WorkId"	INTEGER,
	FOREIGN KEY("WorkId") REFERENCES "Works"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Products" (
	"id"	INTEGER,
	"name"	VARCHAR(255),
	"description"	TEXT,
	"price"	FLOAT,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"CategoryId"	INTEGER,
	FOREIGN KEY("CategoryId") REFERENCES "Categories"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "ProductTag" (
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"ProductId"	INTEGER NOT NULL,
	"TagId"	INTEGER NOT NULL,
	FOREIGN KEY("ProductId") REFERENCES "Products"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("TagId") REFERENCES "Tags"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("ProductId","TagId")
);
CREATE TABLE IF NOT EXISTS "Profiles" (
	"id"	INTEGER,
	"user_id"	UUIDV4 NOT NULL,
	"firstname"	TEXT,
	"lastname"	TEXT,
	"date_of_birth"	DATETIME,
	"orders"	NUMBER,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"UserId"	INTEGER,
	FOREIGN KEY("UserId") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Orders" (
	"id"	INTEGER,
	"date"	DATETIME,
	"price"	NUMBER,
	"order_value"	NUMBER,
	"status"	TEXT,
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"UserId"	INTEGER,
	FOREIGN KEY("UserId") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE CASCADE,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "product_has_categories" (
	"createdAt"	DATETIME NOT NULL,
	"updatedAt"	DATETIME NOT NULL,
	"ProductId"	INTEGER NOT NULL,
	"CategoryId"	INTEGER NOT NULL,
	FOREIGN KEY("CategoryId") REFERENCES "Categories"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("ProductId") REFERENCES "Products"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("ProductId","CategoryId")
);
INSERT INTO "SequelizeMeta" VALUES ('20210518123911-category.js');
INSERT INTO "SequelizeMeta" VALUES ('20210518135329-user.js');
INSERT INTO "SequelizeMeta" VALUES ('20210518141703-work.js');
INSERT INTO "SequelizeMeta" VALUES ('20210518141709-tag.js');
INSERT INTO "SequelizeMeta" VALUES ('20210518164130-work-asset.js');
INSERT INTO "Orders" VALUES (1,'Invalid date',1000,2,'completed','2021-05-20 13:21:40.873 +00:00','2021-05-20 13:21:40.873 +00:00',NULL);
INSERT INTO "Orders" VALUES (2,'Invalid date',1000,2,'completed','2021-05-20 13:22:31.420 +00:00','2021-05-20 13:22:31.420 +00:00',NULL);
COMMIT;
